# Generated by Django 4.2.6 on 2023-11-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweatherapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('temperature_fahrenheit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('feels_like', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weather_description', models.TextField(default='No Description', max_length=255)),
                ('humidity', models.CharField(max_length=5)),
                ('user_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sweatherapp.userpreference')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
