# Generated by Django 4.2.6 on 2023-11-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='city_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='weather_condition',
            field=models.CharField(max_length=250),
        ),
    ]
