# Generated by Django 4.2.6 on 2023-11-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatherapp', '0002_alter_weatherdata_city_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='temperature_celsius',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='wind_speed',
            new_name='temperature_fahrenheit',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='weather_condition',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='feels_like',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='weather_description',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='city_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.IntegerField(),
        ),
    ]
