# Generated by Django 4.2.6 on 2023-11-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatherapp', '0003_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='weather_description',
            field=models.CharField(max_length=255),
        ),
    ]
