# Generated by Django 4.2.6 on 2023-11-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatherapp', '0004_alter_weatherdata_weather_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='lon',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
