# Generated by Django 4.2.6 on 2023-11-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatherapp', '0007_remove_weatherdata_temperature_unit_userpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='feels_like',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature_fahrenheit',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
