# Generated by Django 4.2.6 on 2023-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatherapp', '0008_alter_weatherdata_feels_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.CharField(max_length=5),
        ),
    ]
