# Generated by Django 4.2.6 on 2023-11-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweatherapp', '0009_alter_weatherdata_humidity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['city_name']},
        ),
    ]
